Change "presets" to "questions"
aaact-aatia/a11y-ict-wizard pull request #59
Opened 2024-06-06 13:59 UTC by ocelph

Change variables and text from "presets" to "questions" everywhere applicable for the future change of using questions instead of presets.

2024-06-13 17:17 UTC, benjamin-rolleman requested changes
mainly we need to figure out a way to make sure that the "presets" data is copied over, or at least if it is empty the page loads

2024-06-13 17:17 UTC, benjamin-rolleman commented on models/questionSchema.js
so I checked out this request and tried to run it (I'm trying to simulate a "deploy" on the servers, and I'm not sure exactly what is wrong, but it seems like the new "questions" is not being found. here is the error. from the browser: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at Function.Model.$wrapCallback (/mnt/c/Users/broll/workspace/a11y-ict-wizard/node_modules/mongoose/lib/model.js:5095:32)
    at promiseOrCallback (/mnt/c/Users/broll/workspace/a11y-ict-wizard/node_modules/mongoose/lib/query.js:4510:21)
    at promiseOrCallback (/mnt/c/Users/broll/workspace/a11y-ict-wizard/node_modules/mongoose/lib/helpers/promiseOrCallback.js:10:12)
    at model.Query.exec (/mnt/c/Users/broll/workspace/a11y-ict-wizard/node_modules/mongoose/lib/query.js:4509:10)
    at exports.question_list (/mnt/c/Users/broll/workspace/a11y-ict-wizard/controllers/questionController.js:34:6)
    at Layer.handle [as handle_request] (/mnt/c/Users/broll/workspace/a11y-ict-wizard/node_modules/express/lib/router/layer.js:95:5)
    at next (/mnt/c/Users/broll/workspace/a11y-ict-wizard/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/mnt/c/Users/broll/workspace/a11y-ict-wizard/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/mnt/c/Users/broll/workspace/a11y-ict-wizard/node_modules/express/lib/router/layer.js:95:5)
    at /mnt/c/Users/broll/workspace/a11y-ict-wizard/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/mnt/c/Users/broll/workspace/a11y-ict-wizard/node_modules/express/lib/router/index.js:335:12)
    at next (/mnt/c/Users/broll/workspace/a11y-ict-wizard/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/mnt/c/Users/broll/workspace/a11y-ict-wizard/node_modules/express/lib/router/index.js:174:3)
    at router (/mnt/c/Users/broll/workspace/a11y-ict-wizard/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/mnt/c/Users/broll/workspace/a11y-ict-wizard/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/mnt/c/Users/broll/workspace/a11y-ict-wizard/node_modules/express/lib/router/index.js:317:13)

If it helps perhaps we can meet and I can show you what is going on as it might make it easier to resolve this one.

2024-06-13 17:19 UTC, ocelph commented on README.md
> +In contrast to the overly simple "question" solution, selecting each requirement manually is time consuming and requires strong knowledge of the EN 301 549 standard. A "wizard" style was chosen as a
done

2024-06-14 17:06 UTC, benjamin-rolleman approved these changes

2024-06-14 19:26 UTC, benjamin-rolleman approved these changes

2024-06-14 19:27 UTC, benjamin-rolleman approved these changes

2024-06-14 19:33 UTC, benjamin-rolleman approved these changes

2024-06-17 13:45 UTC, merged